name: myhairregimen
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  shared_preferences: ^0.5.6
  flutter_signin_button: ^1.1.0

  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.8.1


  firebase_core: ^0.5.2+1
  firebase_auth: ^0.18.0+3
  google_sign_in: ^4.5.6
  cloud_firestore: ^0.14.3
  provider: ^3.1.0+9
  table_calendar: ^2.2.3
  image_picker: ^0.6.3
  path: ^1.6.4
  path_provider: ^1.5.1
  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_staggered_grid_view: ^0.3.2
  auto_size_text: ^2.1.0
  font_awesome_flutter: ^8.5.0
  smooth_star_rating: ^1.0.3
  sqflite:
  intl: ^0.16.0
  share: ^0.6.5+3
  mvc_application: ^5.7.0

flutter_icons:
  image_path: "assets/media/launcher/launcher.png"
  ios: true
  android: true

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 600
  assets:
    - assets/media/bottom_bar_icons/
    - assets/media/launcher/
    - assets/media/routine_images/
    - assets/media/routine_images/details/
    - assets/media/sample_products/
    - assets/media/sample_profile/
    - assets/media/hair_icons/
    - assets/media/quiz/
    - assets/media/quiz/Answers/HairPorosity/
    - assets/media/quiz/Answers/CurlPattern/
    - assets/media/quiz/Answers/HairDensity/
    - assets/media/quiz/Answers/HairStructure/


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #   - family: Trajan Pros
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
